version: '3'
services:
  php:
    build:
      context: ./docker-src/php
    container_name: php
    env_file:
    - environment
    volumes:
    - .:/indie-dev-shop
    networks:
    - connector

  app:
    image: webdevops/apache:alpine
    container_name: app
    environment:
    - WEB_PHP_SOCKET=php:9000
    - WEB_DOCUMENT_ROOT=/indie-dev-shop/web
    ports:
    - 8080:80
    volumes:
    - .:/indie-dev-shop
    networks:
    - connector

  db:
    image: mariadb
    container_name: db
    environment:
    - MYSQL_ROOT_PASSWORD=root
    env_file:
    - environment
    ports:
    - 3306:3306
    volumes:
    - database:/var/lib/mysql
    networks:
    - connector

networks:
  connector: {}

volumes:
  database: {}
